#+TITLE:   Bootstrap Confidence Intervals
#+AUTHOR:    
#+EMAIL:     gkerns@ysu.edu
#+DATE:      STAT 5840: Summer 2011
#+LANGUAGE:  en
#+OPTIONS:   H:4 toc:nil author:nil ^:nil num:nil
#+EXPORT_EXCLUDE_TAGS: answer
#+BABEL: :session *R* :results output pp :tangle yes
#+LaTeX_CLASS: article
#+LaTeX_CLASS_OPTIONS: [11pt,english]
#+LATEX_HEADER: \input{handoutformat}
#+latex: \thispagestyle{empty}

* Finding bootstrap confidence intervals for a ratio estimator[fn:1]
We were talking about the =patch= data in the =bootstrap= package which concerns bloodstream measurements for eight subjects in a study. 

#+begin_src R :exports none
library(bootstrap)
data(patch)
head(patch)
#+end_src

The parameter of interest was
\[
\theta = \frac{\E[\mathrm{new}] - \E[\mathrm{old}]}{\E[\mathrm{old}] - \E[\mathrm{placebo}]},
\]
which we estimated with the statistic \(\hat{\theta} = \overline{Y}/\overline{Z}\).  The following uses the bootstrap to find confidence intervals for $\hat{\theta}$.

#+begin_src R :exports code
# bootCIs.R
library(boot)       #for boot and boot.ci
data(patch, package = "bootstrap")

theta.boot <- function(dat, ind) {
  #function to compute the statistic
  y <- dat[ind, 1]
  z <- dat[ind, 2]
  mean(y) / mean(z)
}

y <- patch$y
z <- patch$z
dat <- cbind(y, z)
bootpatch <- boot(dat, statistic = theta.boot, R = 2000)
#+end_src

* Take a look at the results
After the copy-paste of the above we may look at our results with the following.
#+begin_src R :exports both
bootpatch
boot.ci(bootpatch, type = c("basic", "norm", "perc", "bca"))
#+end_src

* Check our answers
We can even check that our intervals are doing what they are supposed to with the following code.

#+begin_src R :exports both
alpha <- c(.025, .975)

#normal
bootpatch$t0 + qnorm(alpha) * sd(bootpatch$t)

#basic
2*bootpatch$t0 - quantile(bootpatch$t, rev(alpha), type=1)

#percentile
quantile(bootpatch$t, alpha, type=6)
#+end_src

Notice that the normal interval is a little bit off, and it's off exactly by the bootstrap estimate of bias.

[fn:1] Adapted from \emph{Statistical Computing with R} by Maria Rizzo (2008). 
