#+TITLE:   Jackknife After Bootstrap
#+AUTHOR:    
#+EMAIL:     gkerns@ysu.edu
#+DATE:      STAT 5840: Summer 2011
#+LANGUAGE:  en
#+OPTIONS:   H:4 toc:nil author:nil ^:nil num:nil
#+EXPORT_EXCLUDE_TAGS: answer
#+BABEL: :session *R* :results output pp :tangle yes
#+LaTeX_CLASS: article
#+LaTeX_CLASS_OPTIONS: [11pt,english]
#+LATEX_HEADER: \input{handoutformat}
#+latex: \thispagestyle{empty}

* Estimating the standard error of a bootstrap standard error estimate
We go back to the =patch= data in the =bootstrap= package which concerns bloodstream measurements for eight subjects in a study. The parameter of interest was
\[
\theta = \frac{\E[\mathrm{new}] - \E[\mathrm{old}]}{\E[\mathrm{old}] - \E[\mathrm{placebo}]},
\]
which we estimated with the statistic \(\hat{\theta} = \overline{Y}/\overline{Z}\).  We can use the boostrap to estimate the standard error of $\hat{\theta}$ which will give us an estimate $\widehat{\mathrm{SE}}(\hat{\theta})$.  But $\widehat{\mathrm{SE}}(\hat{\theta})$ is just an estimator, so it has a standard error, too.  We can use the jackknife-after-bootstrap method to estimate this standard error, and this method is demonstrated below by the following example.

#+begin_src R :exports both
# jackknife4.R
# initialize
data(patch, package = "bootstrap")
n <- nrow(patch)
y <- patch$y
z <- patch$z
B <- 2000
theta.b <- numeric(B)
# set up storage for the sampled indices
indices <- matrix(0, nrow = B, ncol = n)

# step one run the bootstrap
for (b in 1:B) {
  i <- sample(1:n, size = n, replace = TRUE)
  y <- patch$y[i]
  z <- patch$z[i]
  theta.b[b] <- mean(y) / mean(z)
  #save the indices for the jackknife
  indices[b, ] <- i
}

# step two run jackknife on bootstrap replicates
se.jack <- numeric(n)
for (i in 1:n) {
  #in i-th replicate omit all samples with x[i]
  keep <- (1:B)[apply(indices, MARGIN = 1,
                      FUN = function(k) {!any(k == i)})]
  se.jack[i] <- sd(theta.b[keep])
}
#+end_src


After the copy-paste of the above we may look at our results with the following.
#+begin_src R :exports both
sd(theta.b)
sqrt((n-1) * mean((se.jack - mean(se.jack))^2))
#+end_src

So our bootstrap estimate of the standard error is about SRC_R[:results value]{round(sd(theta.b),3)} and our jackknife-after-bootstrap estimate of its standard error is about SRC_R[:results value]{round(sqrt((n-1) * mean((se.jack - mean(se.jack))^2)),3)}.


